### PR TITLE
_ExampleInExampleParser.parse produces and InvalidArgumentError

### PR DESCRIPTION
**Pull request by johnvorsten**
The pad_fn() in _ExampleInExampleParser.parse causes TFRecord protos to be appended with empty byte strings.  When this happens, I've been getting an 
InvalidArgumentError: Name: <unknown>, Feature: relevance (data type: float) is required but could not be found.
	 [[{{node ParseExample_1/ParseExample}}]] [Op:IteratorGetNextSync]

telling me the name 'relevance' cannot be found.  I suspected this is because the feature 'relevance' is not included in the padded list.  Also, the parser behaves correctly when I pass None as _LIST_SIZE.

My solution is to pad the example list with replicas of other protos in the list, but with empty values as their features.  

Please let me know if I can add more information.  I also documented this on SO at https://stackoverflow.com/questions/58003010/tensorflow-tfrecords-cannot-parse-serialized-example/58020973#58020973

### CODE REVIEW

**Comment by johnvorsten** [comment]
@googlebot I signed it!

**Comment by johnvorsten** [comment]
I see that the sequence parser has a default_values for padding.  I did not see that option with _ExampleInExampleParser.  Did I miss something?

**Comment by xuanhuiwang** [comment]
Have you provided a default_value in your feature_spec? This error should be resolved if you provide that.

**Comment by johnvorsten** [comment]
> Have you provided a default_value in your feature_spec? This error should be resolved if you provide that.
Thank you for the tip; that fixed my issue

**Pull request closed without merging**
