### PR TITLE
support crossed feature, branched features

### PR DESCRIPTION
**Pull request by cloverrose**
Hi,
I used this library and found I cannot use crossed feature.
Because crossed feature has one name (dict key) but it depends on 2 values.
Also I have to feed duplicate value if I want to use both numeric feature and its bucketized feature.

I think it is not better to call get_feed_feature_names function each time.
But I have no idea about it without breaking encode_listwise_features I/F.

### CODE REVIEW

**Comment by eggie5** [comment]
can you share some example code using this?

**Comment by xuanhuiwang** [comment]
For cross-features, can you put your logic into score_fn? You can obtain the two features from `group_features` and generate a new with name "crossed_feature" by the operator that you want to do the cross?

For numerical and bucketized features, you may want to use a different name like "feature_bucketized" in the feature column definition for a feature named "feature". Both "feature" and "feature_bucketized" will be kept after encoding in `transform_fn`.

Let me know how this works.

**Comment by cloverrose** [comment]
this is toy sample code (some function copied from [tf_ranking_libsvm.py](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py)

```python
import functools
import random
import numpy as np
import tensorflow as tf
import tensorflow_ranking as tfr

group_size = 1
list_size = 10


class IteratorInitializerHook(tf.train.SessionRunHook):
  """Hook to initialize data iterator after session is created."""

  def __init__(self):
    super(IteratorInitializerHook, self).__init__()
    self.iterator_initializer_fn = None

  def after_create_session(self, session, coord):
    """Initialize the iterator after the session has been created."""
    del coord
    self.iterator_initializer_fn(session)


def create_gen(list_size):
  """
  toy sample data
  s1 == s2 is positive signal
  """
  def gen():
    for i in range(100):
      good_idx = random.randrange(list_size)
      labels = np.zeros([list_size], dtype=np.float32)
      labels[good_idx] = 1.0

      s1 = np.full([list_size, 1], '_', dtype=np.object)
      s2 = np.full([list_size, 1], '_', dtype=np.object)

      for i in range(list_size):
        s1[i, 0] = 'v{0}'.format(random.randrange(100))
        s2[i, 0] = 'v{0}'.format(random.randrange(100))
      s2[good_idx, 0] = s1[good_idx, 0]

      feature_map = {
        's1': s1,
        's2': s2
      }
      yield feature_map, labels
  return gen


def get_train_inputs(list_size, batch_size, train=True):
  """Set up training input in batches."""
  iterator_initializer_hook = IteratorInitializerHook()

  def _train_input_fn():
    """Defines training input fn."""
    dataset = tf.data.Dataset.from_generator(
      create_gen(list_size),
      output_types=({'s1': tf.string, 's2': tf.string}, tf.float32),
      output_shapes=({'s1': tf.TensorShape([list_size, 1]), 's2': tf.TensorShape([list_size, 1])}, tf.TensorShape([list_size]))
    )
    if train:
      dataset = dataset.shuffle(batch_size).repeat()
    dataset = dataset.batch(batch_size)
    iterator = dataset.make_initializable_iterator()
    iterator_initializer_hook.iterator_initializer_fn = (
        lambda sess: sess.run(iterator.initializer))
    return iterator.get_next()

  return _train_input_fn, iterator_initializer_hook


def example_feature_columns():
  crossed1 = tf.feature_column.embedding_column(tf.feature_column.crossed_column(['s1', 's2'], 10000), 8)
  return {'crossed1': crossed1}  # does not contain s1 and s2


def make_score_fn():
  """Returns a groupwise score fn to build `EstimatorSpec`."""

  def _score_fn(unused_context_features, group_features, mode, unused_params,
                unused_config):
    """Defines the network to score a group of documents."""
    with tf.name_scope("input_layer"):
      group_input = [
          tf.layers.flatten(group_features[name])
          for name in sorted(example_feature_columns())
      ]
      input_layer = tf.concat(group_input, 1)
      tf.summary.scalar("input_sparsity", tf.nn.zero_fraction(input_layer))
      tf.summary.scalar("input_max", tf.reduce_max(input_layer))
      tf.summary.scalar("input_min", tf.reduce_min(input_layer))

    is_training = (mode == tf.estimator.ModeKeys.TRAIN)
    cur_layer = tf.layers.batch_normalization(input_layer, training=is_training)
    for i, layer_width in enumerate(int(d) for d in [64, 32]):
      cur_layer = tf.layers.dense(cur_layer, units=layer_width)
      cur_layer = tf.layers.batch_normalization(cur_layer, training=is_training)
      cur_layer = tf.nn.relu(cur_layer)
      tf.summary.scalar("fully_connected_{}_sparsity".format(i),
                        tf.nn.zero_fraction(cur_layer))
    cur_layer = tf.layers.dropout(
        cur_layer, rate=0.5, training=is_training)
    logits = tf.layers.dense(cur_layer, units=group_size)
    return logits

  return _score_fn


def get_eval_metric_fns():
  """Returns a dict from name to metric functions."""
  metric_fns = {}
  metric_fns.update({
      "metric/%s" % name: tfr.metrics.make_ranking_metric_fn(name) for name in [
          tfr.metrics.RankingMetricKey.ARP,
          tfr.metrics.RankingMetricKey.ORDERED_PAIR_ACCURACY,
      ]
  })
  metric_fns.update({
      "metric/ndcg@%d" % topn: tfr.metrics.make_ranking_metric_fn(
          tfr.metrics.RankingMetricKey.NDCG, topn=topn)
      for topn in [1, 3, 5, 10]
  })
  return metric_fns


def train_and_eval():
  """Train and Evaluate."""
  batch_size = 100


  train_input_fn, train_hook = get_train_inputs(list_size, batch_size, train=True)
  vali_input_fn, vali_hook = get_train_inputs(list_size, batch_size, train=False)

  def _train_op_fn(loss):
    """Defines train op used in ranking head."""
    return tf.contrib.layers.optimize_loss(
        loss=loss,
        global_step=tf.train.get_global_step(),
        learning_rate=0.01,
        optimizer="Adagrad")

  ranking_head = tfr.head.create_ranking_head(
      loss_fn=tfr.losses.make_loss_fn("pairwise_logistic_loss"),
      eval_metric_fns=get_eval_metric_fns(),
      train_op_fn=_train_op_fn)

  transform_fn = functools.partial(tfr.feature.encode_listwise_features,
                                   input_size=list_size,
                                   context_feature_columns=None,
                                   example_feature_columns=example_feature_columns())

  estimator = tf.estimator.Estimator(
      model_fn=tfr.model.make_groupwise_ranking_fn(
          group_score_fn=make_score_fn(),
          group_size=group_size,
          transform_fn=transform_fn,
          ranking_head=ranking_head),
      config=tf.estimator.RunConfig(
          '/var/data/output', save_checkpoints_steps=1000))

  train_spec = tf.estimator.TrainSpec(
      input_fn=train_input_fn,
      hooks=[train_hook],
      max_steps=1000)
  vali_spec = tf.estimator.EvalSpec(
      input_fn=vali_input_fn,
      hooks=[vali_hook],
      steps=1,
      start_delay_secs=0,
      throttle_secs=30)

  # Train and validate
  tf.estimator.train_and_evaluate(estimator, train_spec, vali_spec)
```

and its output
```
INFO:tensorflow:Saving dict for global step 1000: global_step = 1000, labels_mean = 0.1, logits_mean = -1.3286384, loss = 0.11608546, metric/arp = 1.2, metric/ndcg@1 = 0.82, metric/ndcg@10 = 0.93094873, metric/ndcg@3 = 0.93094873, metric/ndcg@5 = 0.93094873, metric/ordered_pair_accuracy = 0.9766667
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: /var/data/output/model.ckpt-1000
INFO:tensorflow:Loss for final step: 0.17404887.
```

**Comment by cloverrose** [comment]
xuanhuiwang
Thank you for your comment.
I couldn't think such an idea.
Would you like to tell me example code about such a score_fn?

**Comment by xuanhuiwang** [comment]
Your example code looks fine to me. Another variant is to keep the example_feature_columns() return both s1 and s2 separately.

In the _transoform_fn, you can set the arg example_feature_columns as {'crossed1': tf.feature_column.embedding_column(tf.feature_column.crossed_column(['s1', 's2'], 10000), 8)}

**Comment by cloverrose** [comment]
Hi xuanhuiwang, thank you for your reviews.

What tasks are there left?
Or should tfr's encode_listwise_features be kept for basic case to avoid calling get_feed_feature_names function each time?

**Comment by xuanhuiwang** [comment]
I think so. Since encode_listwise_features is compatible with feature_columns, so all the customization should be done using feature columns library but keep the encoding as simple as possible.

If you agree, can you remove this pull request? Thanks!

**Comment by cloverrose** [comment]
I agree with you.

**Pull request closed without merging**
